version: "3.8"

services:
  contact360-api:
    container_name: contact360-api
    image: node
    volumes:
      - ./app:/usr/src/
    working_dir: /usr/src/
    ports:
      - "3000:3000"
    command: npm start
